name: Ka0s Inspector
on:
  workflow_dispatch:
    inputs:
      kaos-issue-id:
        description: 'Issue ID'
        default: ""
        required: false
      kaos-workflow-id:
        description: 'Workflow ID'
        default: ""
        required: false
      kaos-user-start:
        description: 'User initiated process'
        default: ""
        required: false
permissions:
  contents: write
  actions: write
env:
  KAOS_MODULE: "[Ka0S] INSPECTOR"
  KAOS_OUTPUT_EXECUTION: "audit/inspector/" # Variable de repositorio global
  KAOS_EXP_FULL_LOGS: "conclusion,createdAt,databaseId,event,headBranch,headSha,name,status,updatedAt,url,workflowDatabaseId" # Variables de repositorio global
  KAOS_REPO: "/actions-runner/_work/kaos/kaos" # Variable de repositorio global
jobs:
  job-core:
    runs-on:
      group: swarm-runners
    steps:
      - id: repo
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }} 
      - id: check-data
        name: Check Information
        env:
          GH_TOKEN: ${{ secrets.KAOS_ACTIONS_TOKEN }}
          MAX_ATTEMPTS: ${{ env.MAX_ATTEMPTS || 5 }} # Número máximo de intentos
          SLEEP_SECONDS: ${{ env.SLEEP_SECONDS || 10 }} # Intervalo entre intentos
        run: |
          echo "Checking the execution of the workflow..."
          ATTEMPT=1
          SUCCESS=false
          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            gh run view -v ${{ github.event.inputs.kaos-workflow-id }} --log > ${{ env.KAOS_OUTPUT_EXECUTION }}${{ github.event.inputs.kaos-workflow-id }}.log 2>/dev/null
            gh run view -v ${{ github.event.inputs.kaos-workflow-id }} --json ${{ env.KAOS_EXP_FULL_LOGS }} > ${{ env.KAOS_OUTPUT_EXECUTION }}${{ github.event.inputs.kaos-workflow-id }}.json 2>/dev/null
            if [ $? -eq 0 ]; then
              SUCCESS=true
              break
            else
              echo "Intento $ATTEMPT: El workflow aún está en curso o hubo un error. Reintentando en $SLEEP_SECONDS segundos..."
              sleep $SLEEP_SECONDS
              ATTEMPT=$((ATTEMPT+1))
            fi
          done
          if [ "$SUCCESS" = false ]; then
            echo "No se pudo extraer los logs después de $MAX_ATTEMPTS intentos."
            exit 1
          fi
          echo "Extract resume of execution code..."
          gh run view -v ${{ github.event.inputs.kaos-workflow-id }} --json ${{ env.KAOS_EXP_FULL_LOGS }} > ${{ env.KAOS_OUTPUT_EXECUTION }}${{ github.event.inputs.kaos-workflow-id }}.json
      - id: upload-files
        name: Upload Files
        run: |
          echo "Uploading files to the repository..."
          git config --global user.name "${{ secrets.KAOS_BOT_NAME }}"
          git config --global user.email "${{ secrets.KAOS_BOT_EMAIL }}"
          git pull --rebase
          git add ${{ env.KAOS_OUTPUT_EXECUTION }}
          git commit -m "[Ka0S] Inspector uploading resume execution files to the repository..." || echo "No changes to commit"
          MAX_RETRIES=5
          COUNT=0
          until git push origin ${{ github.ref }} --force-with-lease; do
            COUNT=$((COUNT+1))
            if [ $COUNT -ge $MAX_RETRIES ]; then
              echo "❌ Error: git push failed after $MAX_RETRIES attempts."
              exit 1
            fi
            echo "⚠️ git push failed, retrying ($COUNT/$MAX_RETRIES)..."
            git pull --rebase
            sleep 2
          done
  handle-success:
    runs-on:
      group: swarm-runners
    needs: [job-core]
    if: ${{ success() }}
    steps: 
      - id: handle-success-execution
        run: |
          # Si todo ha ido correctamente pasamos la tarjeta a done
          # Añadimos a cada paso el mensaje de éxito incluido en la issue original
          echo "${{ env.KAOS_MODULE }} Success in runid XXX initiated by ${{ github.event.inputs.kaos-user-start }} through issue number ${{ github.event.inputs.kaos-issue-id }}."
          echo "La ejecución solicitada en el issue ${{ github.event.inputs.kaos-issue-id }} ha sido completada con éxito."
          echo "El código ejecutado y el log de su ejecución se encuentran en ${{ env.KAOS_OUTPUT_EXECUTION }} clave ${{ github.event.inputs.kaos-workflow-id }}"
          echo "Se añaden los ficheros de la ejecución ${{ github.event.inputs.kaos-issue-id }} al repositorio."
          if [ -z "${{ github.event.inputs.kaos-issue-id }}" ]; then
            echo "No se ha encontrado el issue asociado a la ejecución."
          else
            echo "Se ha encontrado el issue asociado a la ejecución."
          fi       
  handle_failure:
    runs-on:
      group: swarm-runners
    needs: [job-core, handle-success]
    if: ${{ failure() }}
    steps:
      - id: handle-failure-execution
        run: |
          echo "Error detected in process"
          echo "Created issue"
          gh issue create  --title "${{ env.KAOS_MODULE }} Error detected in ${{ env.KAOS_CODE }}" --label "bug" --body "Please check the logs 'https://github.com/Ka0s-Klaus/ka0s/actions/runs/${{ env.KAOS_CODE }}' for more information of error."
          