name: Ka0s Re-run Failed Inspector Workflows

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

env:
    KAOS_CODE: ${{ github.run_id }}
    KAOS_EVENT_NAME: ${{ github.event_name }}
    KAOS_ACTION: ${{ github.action }}
    KAOS_REF: ${{ github.ref }}
    KAOS_MODULE: "[Ka0S] Re-Run Failed Inspector Workflows"
    KAOS_PATH_SOURCE: "core/outputs/w/kaos-workflows-runs.json"
    KAOS_PATH_RESUME: "core/results/rr/"
    KAOS_ACTOR: ${{ github.actor }}

permissions:
  actions: write

jobs:
  job-core:
    runs-on:
      group: ka0s
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_REPO_TOKEN }}

      - name: Get failed workflow runs for inspector.yml
        id: get-failed-runs
        env:
          GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
        run: |
          failed_runs=$(jq -r '.[] | select(.name == "Ka0s Inspector" and .conclusion == "failure") | .id' ${{ env.KAOS_PATH_SOURCE }} | tr '\n' ' ')
          echo "Failed runs: $failed_runs"
          echo "::set-output name=failed_runs::${failed_runs}"

      - name: Re-run failed workflows
        id: re-run-failed-workflows
        if: steps.get-failed-runs.outputs.failed_runs != ''
        env:
          GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
        run: |
          for run_id in ${{ steps.get-failed-runs.outputs.failed_runs }}; do
            echo "Re-running: workflow $run_id" >> ${{ env.KAOS_PATH_RESUME }}${{ env.KAOS_CODE }}_resume_reruns_inspector.log
            if ! gh run rerun $run_id --failed; then
              echo "Failed: to rerun job $run_id" >> ${{ env.KAOS_PATH_RESUME }}${{ env.KAOS_CODE }}_resume_reruns_inspector.log
              # gh issue create --title "Failed to rerun job $file" --body "Failed to automatically rerun job $file which contained error patterns. Please investigate manually."
            else
              echo "Successfully: rerun job $run_id" >> ${{ env.KAOS_PATH_RESUME }}${{ env.KAOS_CODE }}_resume_reruns_inspector.log
              # gh issue create --title "Successfully rerun job $file" --body "Job $file was successfully rerun after detecting error patterns."
            fi
          done

      - name: Upload file results
        id: upload-files
        if: steps.get-failed-runs.outputs.failed_runs != ''
        run: |
          echo "Uploading results files to the repository..."
          git config --global user.name "${{ secrets.KAOS_BOT_NAME }}"
          git config --global user.email "${{ secrets.KAOS_BOT_EMAIL }}"
          git pull
          git add ${{ env.KAOS_PATH_RESUME }}*
          git commit -m "[Ka0S] Re-Runs Inspector uploading resume execution files to the repository..."
          git push

  handle-success:
            runs-on:
              group: ka0s
            needs: [job-core]
            if: ${{ success() }}
            steps:
              - id: repo
                name: Checkout code
                if: ${{ always() }}
                uses: actions/checkout@v4
                with:
                  fetch-depth: 0
                  token: ${{ secrets.KAOS_REPO_TOKEN }}
              - id: handle-success-execution
                name: handle-success-execution
                env:
                  GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
                run: |
                  # RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
                  # gh issue comment $RNNUMBER --body "El proceso ha finalizado correctamente ${{ env.KAOS_CODE }}. El resultado está en el fichero core/results/event_data_${{ env.KAOS_CODE }}.log"
                  echo "El proceso ha finalizado correctamente ${{ env.KAOS_CODE }}. El resultado está en el fichero core/results/event_data_${{ env.KAOS_CODE }}.log"
  
  handle_failure:
            runs-on:
              group: ka0s
            needs: [job-core, handle-success]
            if: ${{ failure() }}
            steps:
              - id: repo
                name: Checkout code
                if: ${{ always() }}
                uses: actions/checkout@v4
                with:
                  fetch-depth: 0
                  token: ${{ secrets.KAOS_REPO_TOKEN }}
              - id: handle-failure-execution
                name: handle-failure-execution
                env:
                  GH_TOKEN: ${{ secrets.KAOS_REPO_TOKEN }}
                run: |
                  echo "Error detected in process"
                  # RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
                  # gh issue comment $RNNUMBER --body "El proceso no ha finalizado correctamente ${{ env.KAOS_CODE }}. El resultado está en el fichero core/results/event_data${{ env.KAOS_CODE }}.log"
                  # Creamos la issue dado que ha fallado el modulo principal
                  gh issue create  --title "[Ka0S] Error detected in ${{ env.KAOS_MODULE }}" --body "Error detected in ${{ env.KAOS_MODULE }}. Please check the logs for ${{ github.run_id }} more information of error."
          
  end-workflow:
            runs-on:
              group: ka0s
            needs: [job-core, handle-success, handle_failure]
            if: ${{ always() && !contains(github.event.head_commit.message, '[Ka0S] ') }}
            env:
                GH_TOKEN: ${{ secrets.KAOS_ACTIONS_TOKEN }}
            steps:
              - id: repo
                name: Checkout code
                if: ${{ always() }}
                uses: actions/checkout@v4
                with:
                  fetch-depth: 0
                  token: ${{ secrets.KAOS_REPO_TOKEN }}
              - id: end-process
                name: Finaliza el workflow
                run: |
                  echo "End process"
                  # RNNUMBER=$(echo "${{ github.ref }}" | grep -o '[0-9]*')
                  # gh issue comment $RNNUMBER --body "Se finaliza Ka0s ${{ env.KAOS_CODE }}"
                  echo "Se finaliza Ka0s ${{ env.KAOS_CODE }}"
                  gh workflow run inspector.yml --ref 'main' -f kaos-issue-id=$RNNUMBER -f kaos-workflow-id="${{ env.KAOS_CODE }}" -f kaos-user-start=""
        